name: app_buitron_coffee
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Librerías para mostrar mapas
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # Librería para manejar el estado de la aplicación
  provider: ^6.1.5+1

  # Librería para conectar con Supabase (base de datos, auth, etc.)
  supabase_flutter: ^2.17.2

  # Librerías para el panel de administración (peticiones HTTP y token guardado)
  http: ^1.2.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/